\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		s2.

		% estribillo
		f4. bes4. | f4. bes4. |
		f4. c | f2. |
		f4. bes4. | f4. bes4. |
		f4. c | f2. |

		% porque el es yahve...
		d2.:m | c2. |
		f2. | d2.:m |
		bes2. | g2.:m |
		bes2. | c2. | c2. |

		% entremos, adoremos...
		f2. | bes4. f4. |
		f2. | bes4. f4. |
	
		% estribillo
		f4. bes4. | f4. bes4. |
		f4. c | f2. |
		f4. bes4. | f4. bes4. |
		f4. c | f2. |

		% porque el es yahve...
		d2.:m | c2. |
		f2. | d2.:m |
		bes2. | g2.:m |
		bes2. | c2. | c2. |

		% entremos, adoremos...
		f2. | bes4. f4. |
		f2. | bes4. f4. |
	
		% estribillo
		f4. bes4. | f4. bes4. |
		f4. c | f2. |
		f4. bes4. | f4. bes4. |
		f4. c | f2. |
	}
